version: '3'
services:
  api:
    container_name: invoicer-api
    image: null-solutions/invoicer:${VERSION}
    build: .
    ports:
      - "4971:4971"
    environment:
      PGHOST: 'postgres'
      PGDATABASE: 'invoicer'
      PGPORT: 5432
      PGUSER: 'invoicer'
      PGPASSWORD: 'invoicer'

  migrations:
    container_name: migrations
    build:
      dockerfile: Dockerfile.migrations
    environment:
      DATABASE_URL: 'postgres://invoicer:invoicer@postgres:5432/invoicer'
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'invoicer'
      POSTGRES_PASSWORD: 'invoicer'
    volumes:
      - invoicer:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  invoicer:
